version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Preparing artifacts...
      - cp -r ./build ./deploy/build
      - cp -r ./node_modules ./deploy/node_modules
artifacts:
  files:
    - 'deploy/**/*'

deploy:
  commands:
    - echo Deploying and starting the application...
    - cd deploy
    - npm start
